const { test, before } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');
const request = require('supertest');
const { app, paths } = require('./helpers/app');

const SLUG = 'sessions-test-proj';
const SESSION_A = '11111111-1111-1111-1111-111111111111';
const SESSION_B = '22222222-2222-2222-2222-222222222222';
const SESSION_C = '33333333-3333-3333-3333-333333333333';
const SESSION_D = '44444444-4444-4444-4444-444444444444';
const SESSION_E = '55555555-5555-5555-5555-555555555555';
const PROJECT_DIR = path.join(paths.PROJECTS_DIR, SLUG);

function writeJsonl(filePath, entries) {
  const content = entries.map(e => JSON.stringify(e)).join('\n') + '\n';
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf-8');
}

before(() => {
  fs.rmSync(PROJECT_DIR, { recursive: true, force: true });
  fs.mkdirSync(PROJECT_DIR, { recursive: true });

  writeJsonl(path.join(PROJECT_DIR, SESSION_A + '.jsonl'), [
    {
      type: 'user',
      uuid: 'u1',
      parentUuid: null,
      timestamp: '2026-01-01T10:00:00.000Z',
      gitBranch: 'main',
      message: { content: 'Hello from session A about widgets' }
    },
    {
      type: 'assistant',
      uuid: 'a1',
      parentUuid: 'u1',
      timestamp: '2026-01-01T10:00:05.000Z',
      message: { model: 'claude-3-5-sonnet', content: 'Hi, let me help with widgets.' }
    },
    {
      type: 'user',
      uuid: 'u2',
      parentUuid: 'a1',
      timestamp: '2026-01-01T10:00:10.000Z',
      gitBranch: 'main',
      message: { content: 'Second user message with unique-needle-alpha' }
    },
    {
      type: 'assistant',
      uuid: 'a2',
      parentUuid: 'u2',
      timestamp: '2026-01-01T10:00:15.000Z',
      message: { model: 'claude-3-5-sonnet', content: 'Responding to alpha.' }
    },
    {
      type: 'user',
      uuid: 'u3',
      parentUuid: 'a2',
      timestamp: '2026-01-01T10:00:20.000Z',
      gitBranch: 'main',
      message: { content: 'Third message' }
    }
  ]);

  writeJsonl(path.join(PROJECT_DIR, SESSION_C + '.jsonl'), [
    {
      type: 'user', uuid: 'c1', parentUuid: null,
      timestamp: '2026-03-01T08:00:00.000Z',
      gitBranch: 'main',
      message: { content: 'Start work on main' }
    },
    {
      type: 'user', uuid: 'c2', parentUuid: 'c1',
      timestamp: '2026-03-01T08:30:00.000Z',
      gitBranch: 'feature/x',
      message: { content: 'Switched to feature' }
    },
    {
      type: 'user', uuid: 'c3', parentUuid: 'c2',
      timestamp: '2026-03-01T09:00:00.000Z',
      gitBranch: 'main',
      message: { content: 'Back to main' }
    },
    {
      type: 'user', uuid: 'c4', parentUuid: 'c3',
      timestamp: '2026-03-01T09:30:00.000Z',
      gitBranch: 'bugfix/y',
      message: { content: 'Hotfix branch' }
    }
  ]);

  writeJsonl(path.join(PROJECT_DIR, SESSION_B + '.jsonl'), [
    {
      type: 'user',
      uuid: 'u10',
      parentUuid: null,
      timestamp: '2026-02-01T09:00:00.000Z',
      gitBranch: 'feature',
      message: { content: 'Session B first prompt about gadgets' }
    },
    {
      type: 'assistant',
      uuid: 'a10',
      parentUuid: 'u10',
      timestamp: '2026-02-01T09:00:05.000Z',
      message: { model: 'claude-3-5-sonnet', content: 'Gadget reply' }
    }
  ]);

  writeJsonl(path.join(PROJECT_DIR, SESSION_E + '.jsonl'), [
    {
      type: 'user', uuid: 'e1', parentUuid: null,
      timestamp: '2026-05-01T10:00:00.000Z', gitBranch: 'main',
      message: { content: 'Session E with a sub-agent' }
    },
    {
      type: 'assistant', uuid: 'e2', parentUuid: 'e1',
      timestamp: '2026-05-01T10:00:05.000Z',
      message: { model: 'claude-sonnet', content: [{ type: 'tool_use', name: 'Agent', id: 'tu1', input: { description: 'explore widgets', subagent_type: 'Explore', prompt: 'look at widgets' } }] }
    }
  ]);
  writeJsonl(path.join(PROJECT_DIR, SESSION_E, 'subagents', 'agent-abc123.jsonl'), [
    {
      type: 'user', uuid: 's1', parentUuid: null, isSidechain: true, agentId: 'abc123',
      timestamp: '2026-05-01T10:00:06.000Z',
      message: { content: 'look at widgets' }
    },
    {
      type: 'assistant', uuid: 's2', parentUuid: 's1', isSidechain: true, agentId: 'abc123',
      timestamp: '2026-05-01T10:00:08.000Z',
      message: { content: [{ type: 'text', text: 'Found the unique-subagent-needle result here.' }] }
    }
  ]);

  writeJsonl(path.join(PROJECT_DIR, SESSION_D + '.jsonl'), [
    {
      type: 'user',
      uuid: 'd1',
      parentUuid: null,
      isMeta: true,
      timestamp: '2026-04-01T10:00:00.000Z',
      gitBranch: 'main',
      message: { content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>' }
    },
    {
      type: 'user',
      uuid: 'd2',
      parentUuid: 'd1',
      timestamp: '2026-04-01T10:00:01.000Z',
      gitBranch: 'main',
      message: { content: '<command-message>n-104-specify</command-message>\n<command-name>/n-104-specify</command-name>\n<command-args>PROJ-1234</command-args>' }
    }
  ]);

});

test('GET /api/projects/:slug/sessions returns array with expected fields', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions`);
  assert.strictEqual(res.status, 200);
  assert.ok(Array.isArray(res.body));
  assert.ok(res.body.length >= 5);
  const ids = res.body.map(s => s.sessionId).sort();
  assert.deepStrictEqual(ids, [SESSION_A, SESSION_B, SESSION_C, SESSION_D, SESSION_E].sort());
  const a = res.body.find(s => s.sessionId === SESSION_A);
  assert.strictEqual(a.messageCount, 3);
  assert.strictEqual(a.gitBranch, 'main');
  assert.ok(a.firstPrompt.includes('Hello from session A'));
  assert.ok('created' in a);
  assert.ok('modified' in a);
});

test('GET /api/projects/:slug/sessions sorts by modified descending', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions`);
  assert.strictEqual(res.status, 200);
  assert.strictEqual(res.body[0].sessionId, SESSION_E);
  assert.strictEqual(res.body[1].sessionId, SESSION_D);
  assert.strictEqual(res.body[2].sessionId, SESSION_C);
  assert.strictEqual(res.body[3].sessionId, SESSION_B);
  assert.strictEqual(res.body[4].sessionId, SESSION_A);
});

test('GET /api/projects/:slug/sessions includes ordered distinct gitBranches', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions`);
  assert.strictEqual(res.status, 200);
  const c = res.body.find(s => s.sessionId === SESSION_C);
  assert.ok(c, 'session C present');
  assert.deepStrictEqual(c.gitBranches, ['main', 'feature/x', 'bugfix/y'],
    'gitBranches should be distinct in first-seen order');
  const a = res.body.find(s => s.sessionId === SESSION_A);
  assert.deepStrictEqual(a.gitBranches, ['main']);
  const b = res.body.find(s => s.sessionId === SESSION_B);
  assert.deepStrictEqual(b.gitBranches, ['feature']);
});

test('GET /api/projects/:slug/sessions includes command-args in firstPrompt', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions`);
  assert.strictEqual(res.status, 200);
  const d = res.body.find(s => s.sessionId === SESSION_D);
  assert.ok(d, 'session D present');
  assert.ok(d.firstPrompt.startsWith('/n-104-specify'), 'firstPrompt starts with command name');
  assert.ok(d.firstPrompt.includes('PROJ-1234'), 'firstPrompt includes command args (ticket reference)');
});

test('GET /api/projects/:slug/sessions with invalid slug returns 400', async () => {
  const res = await request(app).get('/api/projects/bad..slug/sessions');
  assert.strictEqual(res.status, 400);
  assert.strictEqual(res.body.error, 'Invalid slug');
});

test('GET /api/projects/:slug/sessions/search filters by query', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/search`).query({ q: 'unique-needle-alpha' });
  assert.strictEqual(res.status, 200);
  assert.ok(Array.isArray(res.body));
  assert.strictEqual(res.body.length, 1);
  assert.strictEqual(res.body[0].sessionId, SESSION_A);
  assert.ok(Array.isArray(res.body[0].snippets));
  assert.ok(res.body[0].snippets.length >= 1);
  assert.ok(res.body[0].snippets[0].text.toLowerCase().includes('unique-needle-alpha'));
});

test('GET /api/projects/:slug/sessions/search returns empty for short query', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/search`).query({ q: 'a' });
  assert.strictEqual(res.status, 200);
  assert.deepStrictEqual(res.body, []);
});

test('search: query matching sub-agent content returns parent session', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/search`).query({ q: 'unique-subagent-needle' });
  assert.strictEqual(res.status, 200);
  assert.ok(Array.isArray(res.body));
  assert.strictEqual(res.body.length, 1);
  assert.strictEqual(res.body[0].sessionId, SESSION_E);
  assert.ok(res.body[0].snippets.some(s => s.text.toLowerCase().includes('unique-subagent-needle')));
});

test('GET /api/projects/:slug/sessions stamps active=false when nothing is registered', async () => {
  const activeSessions = require('../lib/active-sessions');
  const terminalServer = require('../lib/terminal-server');
  activeSessions._reset();
  terminalServer._clearAll();
  const res = await request(app).get(`/api/projects/${SLUG}/sessions`);
  assert.strictEqual(res.status, 200);
  for (const s of res.body) {
    assert.strictEqual(s.active, false);
    assert.strictEqual(s.activeKind, null);
  }
});

test('GET /api/projects/:slug/sessions stamps active=true, activeKind=os for OS-registered sessions', async () => {
  const activeSessions = require('../lib/active-sessions');
  const terminalServer = require('../lib/terminal-server');
  activeSessions._reset();
  terminalServer._clearAll();
  activeSessions.register(SLUG, SESSION_A, 'os-terminal');
  const res = await request(app).get(`/api/projects/${SLUG}/sessions`);
  assert.strictEqual(res.status, 200);
  const a = res.body.find(s => s.sessionId === SESSION_A);
  assert.strictEqual(a.active, true);
  assert.strictEqual(a.activeKind, 'os');
  const b = res.body.find(s => s.sessionId === SESSION_B);
  assert.strictEqual(b.active, false);
  activeSessions._reset();
});

test('GET /api/projects/:slug/sessions: browser-terminal beats OS in activeKind', async () => {
  const activeSessions = require('../lib/active-sessions');
  const terminalServer = require('../lib/terminal-server');
  activeSessions._reset();
  terminalServer._clearAll();
  activeSessions.register(SLUG, SESSION_A, 'os-terminal');
  terminalServer._injectFakeEntry(SLUG, SESSION_A, { ws: null });
  const res = await request(app).get(`/api/projects/${SLUG}/sessions`);
  assert.strictEqual(res.status, 200);
  const a = res.body.find(s => s.sessionId === SESSION_A);
  assert.strictEqual(a.active, true);
  assert.strictEqual(a.activeKind, 'browser');
  terminalServer._clearAll();
  activeSessions._reset();
});

test('GET /api/projects/:slug/sessions stamps active=true, activeKind=readonly for a read-only-only session', async () => {
  const activeSessions = require('../lib/active-sessions');
  const terminalServer = require('../lib/terminal-server');
  activeSessions._reset();
  terminalServer._clearAll();
  activeSessions.registerReadonly(SLUG, SESSION_A, 'instance-1');
  const res = await request(app).get(`/api/projects/${SLUG}/sessions`);
  assert.strictEqual(res.status, 200);
  const a = res.body.find(s => s.sessionId === SESSION_A);
  assert.strictEqual(a.active, true);
  assert.strictEqual(a.activeKind, 'readonly');
  activeSessions._reset();
});

test('GET /api/projects/:slug/sessions: os and readonly both surface in activeKinds when present together', async () => {
  const activeSessions = require('../lib/active-sessions');
  const terminalServer = require('../lib/terminal-server');
  activeSessions._reset();
  terminalServer._clearAll();
  activeSessions.register(SLUG, SESSION_A, 'os-terminal');
  activeSessions.registerReadonly(SLUG, SESSION_A, 'instance-1');
  const res = await request(app).get(`/api/projects/${SLUG}/sessions`);
  assert.strictEqual(res.status, 200);
  const a = res.body.find(s => s.sessionId === SESSION_A);
  assert.strictEqual(a.active, true);
  // activeKind (primary, single value) still favors the real process for callers that only look at one...
  assert.strictEqual(a.activeKind, 'os');
  // ...but activeKinds carries both, so the UI can render a dot for each.
  assert.deepStrictEqual(a.activeKinds, ['os', 'readonly']);
  activeSessions._reset();
});

test('GET /api/projects/:slug/sessions: browser and readonly both surface in activeKinds when present together', async () => {
  const activeSessions = require('../lib/active-sessions');
  const terminalServer = require('../lib/terminal-server');
  activeSessions._reset();
  terminalServer._clearAll();
  terminalServer._injectFakeEntry(SLUG, SESSION_A, { ws: null });
  activeSessions.registerReadonly(SLUG, SESSION_A, 'instance-1');
  const res = await request(app).get(`/api/projects/${SLUG}/sessions`);
  assert.strictEqual(res.status, 200);
  const a = res.body.find(s => s.sessionId === SESSION_A);
  assert.strictEqual(a.activeKind, 'browser');
  assert.deepStrictEqual(a.activeKinds, ['browser', 'readonly']);
  terminalServer._clearAll();
  activeSessions._reset();
});

test('GET /api/projects/:slug/sessions/search returns empty when no match', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/search`).query({ q: 'zzznonexistentzzz' });
  assert.strictEqual(res.status, 200);
  assert.deepStrictEqual(res.body, []);
});

test('GET /api/projects/:slug/sessions/:sessionId returns paginated messages (default)', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/${SESSION_A}`);
  assert.strictEqual(res.status, 200);
  assert.ok(Array.isArray(res.body.messages));
  assert.strictEqual(res.body.total, 5);
  assert.strictEqual(res.body.messages.length, 5);
  assert.strictEqual(res.body.hasMore, false);
  assert.strictEqual(res.body.messages[0].role, 'user');
  assert.strictEqual(res.body.messages[0].content[0].text, 'Third message');
});

test('GET /api/projects/:slug/sessions/:sessionId includes stats for badge rendering', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/${SESSION_A}`);
  assert.strictEqual(res.status, 200);
  assert.ok(res.body.stats, 'stats field should be present');
  // messageCount counts user messages only (prompts sent); total counts all rendered messages
  assert.strictEqual(res.body.stats.messageCount, 3);
  assert.strictEqual(res.body.total, 5);
  assert.deepStrictEqual(res.body.stats.gitBranches, ['main']);
  assert.strictEqual(res.body.stats.lastGitBranch, 'main');
  assert.strictEqual(res.body.stats.isSidechain, false);
});

test('GET /api/projects/:slug/sessions/:sessionId stats.created is first user message timestamp', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/${SESSION_A}`);
  assert.strictEqual(res.status, 200);
  assert.strictEqual(res.body.stats.created, '2026-01-01T10:00:00.000Z');
});

test('GET /api/projects/:slug/sessions/:sessionId stats.active is true for a read-only viewer instance', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();
  activeSessions.registerReadonly(SLUG, SESSION_A, 'instance-1');

  const res = await request(app).get(`/api/projects/${SLUG}/sessions/${SESSION_A}`);
  assert.strictEqual(res.status, 200);
  assert.strictEqual(res.body.stats.active, true);

  activeSessions._reset();
});

test('GET /api/projects/:slug/sessions/:sessionId stats.remoteControlled is false when no bridge entry', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/${SESSION_A}`);
  assert.strictEqual(res.status, 200);
  assert.strictEqual(res.body.stats.remoteControlled, false);
});

test('GET /api/projects/:slug/sessions/:sessionId stats.remoteControlled is true when JSONL has bridge-session', async () => {
  const bridgeId = 'bridge-ses-4444-4444-4444-444444444444';
  const bridgeEntries = [
    { type: 'bridge-session', timestamp: '2026-01-10T09:00:00.000Z' },
    { type: 'user', timestamp: '2026-01-10T09:00:01.000Z', message: { content: 'from bridge' } }
  ];
  writeJsonl(path.join(PROJECT_DIR, bridgeId + '.jsonl'), bridgeEntries);

  const res = await request(app).get(`/api/projects/${SLUG}/sessions/${bridgeId}`);
  assert.strictEqual(res.status, 200);
  assert.strictEqual(res.body.stats.remoteControlled, true);
});

test('GET /api/projects/:slug/sessions/:sessionId honors offset and limit', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/${SESSION_A}`).query({ offset: 1, limit: 2 });
  assert.strictEqual(res.status, 200);
  assert.strictEqual(res.body.total, 5);
  assert.strictEqual(res.body.messages.length, 2);
  assert.strictEqual(res.body.hasMore, true);
});

test('GET /api/projects/:slug/sessions/:sessionId with unknown id returns 404', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/does-not-exist`);
  assert.strictEqual(res.status, 404);
  assert.strictEqual(res.body.error, 'Session not found');
});

test('GET /api/projects/:slug/sessions/:sessionId rejects traversal in session id', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/..evil`);
  assert.strictEqual(res.status, 400);
  assert.strictEqual(res.body.error, 'Invalid session ID');
});

test('POST /api/projects/:slug/sessions/:sessionId/rename updates custom title', async () => {
  const newTitle = 'Renamed Session Title';
  const res = await request(app)
    .post(`/api/projects/${SLUG}/sessions/${SESSION_B}/rename`)
    .send({ title: newTitle });
  assert.strictEqual(res.status, 200);
  assert.strictEqual(res.body.ok, true);
  assert.strictEqual(res.body.title, newTitle);

  const list = await request(app).get(`/api/projects/${SLUG}/sessions`);
  const b = list.body.find(s => s.sessionId === SESSION_B);
  assert.strictEqual(b.summary, newTitle);
});

test('POST /api/projects/:slug/sessions/:sessionId/rename rejects empty title', async () => {
  const res = await request(app)
    .post(`/api/projects/${SLUG}/sessions/${SESSION_A}/rename`)
    .send({ title: '   ' });
  assert.strictEqual(res.status, 400);
  assert.strictEqual(res.body.error, 'Title is required');
});

test('POST /api/projects/:slug/sessions/:sessionId/rename rejects overly long title', async () => {
  const res = await request(app)
    .post(`/api/projects/${SLUG}/sessions/${SESSION_A}/rename`)
    .send({ title: 'x'.repeat(501) });
  assert.strictEqual(res.status, 400);
  assert.strictEqual(res.body.error, 'Title too long');
});

test('POST /api/projects/:slug/sessions/:sessionId/rename returns 404 for unknown session', async () => {
  const res = await request(app)
    .post(`/api/projects/${SLUG}/sessions/unknown-session/rename`)
    .send({ title: 'Whatever' });
  assert.strictEqual(res.status, 404);
  assert.strictEqual(res.body.error, 'Session not found');
});

test('POST /api/projects/:slug/sessions/new returns ok and registers pending new session', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();

  const res = await request(app).post(`/api/projects/${SLUG}/sessions/new`);
  assert.strictEqual(res.status, 200);
  assert.strictEqual(res.body.ok, true);

  // registerPendingNew was called — a fresh session should resolve as active
  const newId = 'new-session-resolve-test';
  const created = new Date().toISOString();
  activeSessions.resolvePendingNew(SLUG, [{ sessionId: newId, created }]);
  assert.strictEqual(activeSessions.isActive(SLUG, newId, created), true);
});

test('POST /api/projects/:slug/sessions/new returns 400 for invalid slug', async () => {
  const res = await request(app).post('/api/projects/bad..slug/sessions/new');
  assert.strictEqual(res.status, 400);
  assert.strictEqual(res.body.error, 'Invalid slug');
});

test('POST /api/projects/:slug/sessions/:sessionId/resume is skipped (spawns terminal)', { skip: 'Endpoint launches an OS terminal via child_process; testing would open a real window on the runner.' }, () => {});

test('hasBridgeSession: returns true for jsonl with bridge-session entry, false otherwise', () => {
  const { hasBridgeSession } = require('../lib/session-flags');
  const tmpSlug = 'bridge-flag-helper';
  const dir = path.join(paths.PROJECTS_DIR, tmpSlug);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });

  const withBridge = path.join(dir, 'with.jsonl');
  writeJsonl(withBridge, [
    { type: 'user', uuid: 'u', timestamp: '2026-01-01T00:00:00Z', message: { content: 'hi' } },
    { type: 'bridge-session', sessionId: 'sid', bridgeSessionId: 'cse_test', lastSequenceNum: 0 }
  ]);
  const withoutBridge = path.join(dir, 'without.jsonl');
  writeJsonl(withoutBridge, [
    { type: 'user', uuid: 'u', timestamp: '2026-01-01T00:00:00Z', message: { content: 'hi' } }
  ]);

  assert.strictEqual(hasBridgeSession(withBridge), true);
  assert.strictEqual(hasBridgeSession(withoutBridge), false);
  assert.strictEqual(hasBridgeSession(path.join(dir, 'missing.jsonl')), false);
});

test('GET /api/projects/:slug/sessions stamps remoteControlled=true for sessions with bridge-session entries', async () => {
  const tmpSlug = 'bridge-flag-list';
  const dir = path.join(paths.PROJECTS_DIR, tmpSlug);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });

  const REMOTE_SID = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
  const LOCAL_SID = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';

  writeJsonl(path.join(dir, REMOTE_SID + '.jsonl'), [
    { type: 'user', uuid: 'u', timestamp: '2026-01-02T00:00:00Z', gitBranch: 'main', message: { content: 'remote-controlled' } },
    { type: 'bridge-session', sessionId: REMOTE_SID, bridgeSessionId: 'cse_test', lastSequenceNum: 0 }
  ]);
  writeJsonl(path.join(dir, LOCAL_SID + '.jsonl'), [
    { type: 'user', uuid: 'u', timestamp: '2026-01-01T00:00:00Z', gitBranch: 'main', message: { content: 'local only' } }
  ]);

  const res = await request(app).get(`/api/projects/${tmpSlug}/sessions`);
  assert.strictEqual(res.status, 200);
  const remote = res.body.find(s => s.sessionId === REMOTE_SID);
  const local = res.body.find(s => s.sessionId === LOCAL_SID);
  assert.strictEqual(remote.remoteControlled, true);
  assert.strictEqual(local.remoteControlled, false);
});

test('GET /api/projects/:slug/sessions/with-plans returns session IDs whose JSONL references a plan file', async () => {
  const tmpSlug = 'with-plans-test';
  const dir = path.join(paths.PROJECTS_DIR, tmpSlug);
  const plansDir = path.join(paths.CLAUDE_DIR, 'plans');
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });
  fs.mkdirSync(plansDir, { recursive: true });

  const PLAN_STEM = 'test-wiggly-unique-plan-alpha';
  const PLAN_STEM2 = 'test-wiggly-unique-plan-beta';
  fs.writeFileSync(path.join(plansDir, PLAN_STEM + '.md'), '# Plan: Alpha plan\n\nsome content');
  fs.writeFileSync(path.join(plansDir, PLAN_STEM2 + '.md'), '# Plan: Beta plan\n\nsome content');

  const WITH_PLAN = 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee';
  const WITHOUT_PLAN = 'ffffffff-ffff-ffff-ffff-ffffffffffff';
  const WITH_PLAN2 = 'cccccccc-cccc-cccc-cccc-cccccccccccc';

  // Session that references plan via planFilePath (as ExitPlanMode would store it)
  writeJsonl(path.join(dir, WITH_PLAN + '.jsonl'), [
    { type: 'user', uuid: 'u1', timestamp: '2026-01-01T10:00:00Z', message: { content: 'do a plan' } },
    { type: 'assistant', uuid: 'a1', timestamp: '2026-01-01T10:00:05Z', message: { content: [{ type: 'tool_use', id: 't1', name: 'ExitPlanMode', input: { plan: '# Plan: Alpha plan', planFilePath: `C:\\Users\\test\\.claude\\plans\\${PLAN_STEM}.md` } }] } }
  ]);
  // Session with no plan reference
  writeJsonl(path.join(dir, WITHOUT_PLAN + '.jsonl'), [
    { type: 'user', uuid: 'u2', timestamp: '2026-01-01T11:00:00Z', message: { content: 'regular session' } },
    { type: 'assistant', uuid: 'a2', timestamp: '2026-01-01T11:00:05Z', message: { content: 'just a reply' } }
  ]);
  // Session referencing the second plan
  writeJsonl(path.join(dir, WITH_PLAN2 + '.jsonl'), [
    { type: 'user', uuid: 'u3', timestamp: '2026-01-01T12:00:00Z', message: { content: 'another plan session' } },
    { type: 'assistant', uuid: 'a3', timestamp: '2026-01-01T12:00:05Z', message: { content: [{ type: 'tool_use', id: 't2', name: 'ExitPlanMode', input: { plan: '# Plan: Beta plan', planFilePath: `C:\\Users\\test\\.claude\\plans\\${PLAN_STEM2}.md` } }] } }
  ]);

  const res = await request(app).get(`/api/projects/${tmpSlug}/sessions/with-plans`);
  assert.strictEqual(res.status, 200);
  assert.ok(Array.isArray(res.body));
  const ids = res.body.sort();
  assert.ok(ids.includes(WITH_PLAN), 'should include session referencing plan alpha');
  assert.ok(ids.includes(WITH_PLAN2), 'should include session referencing plan beta');
  assert.ok(!ids.includes(WITHOUT_PLAN), 'should not include session without plan reference');
});

test('GET /api/projects/:slug/sessions/with-plans returns empty array when no plans directory exists', async () => {
  const tmpSlug = 'no-plans-test';
  const dir = path.join(paths.PROJECTS_DIR, tmpSlug);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });

  writeJsonl(path.join(dir, 'aaaabbbb-1111-1111-1111-aaaaaaaabbbb.jsonl'), [
    { type: 'user', uuid: 'u1', timestamp: '2026-01-01T10:00:00Z', message: { content: 'hello' } }
  ]);

  // Temporarily hide plans dir if it exists
  const plansDir = path.join(paths.CLAUDE_DIR, 'plans');
  const plansDirTmp = plansDir + '_hidden_tmp';
  const existed = fs.existsSync(plansDir);
  if (existed) fs.renameSync(plansDir, plansDirTmp);

  try {
    const res = await request(app).get(`/api/projects/${tmpSlug}/sessions/with-plans`);
    assert.strictEqual(res.status, 200);
    assert.deepStrictEqual(res.body, []);
  } finally {
    if (existed) fs.renameSync(plansDirTmp, plansDir);
  }
});

test('GET /api/projects/:slug/sessions/with-plans with invalid slug returns 400', async () => {
  const res = await request(app).get('/api/projects/bad..slug/sessions/with-plans');
  assert.strictEqual(res.status, 400);
  assert.strictEqual(res.body.error, 'Invalid slug');
});

test('GET /api/projects/:slug/sessions/:sessionId/activity returns categorized tool calls', async () => {
  const tmpSlug = 'activity-test-proj';
  const sid = 'activ111-1111-1111-1111-111111111111';
  const dir = path.join(paths.PROJECTS_DIR, tmpSlug);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });

  writeJsonl(path.join(dir, sid + '.jsonl'), [
    { type: 'user', uuid: 'u1', timestamp: '2026-01-01T10:00:00Z', message: { content: 'go' } },
    {
      type: 'assistant', uuid: 'a1', timestamp: '2026-01-01T10:00:05Z',
      message: { content: [
        { type: 'tool_use', name: 'Bash', input: { command: 'npm test' } },
        { type: 'tool_use', name: 'Read', input: { file_path: '/src/index.js' } },
        { type: 'tool_use', name: 'WebSearch', input: { query: 'node docs' } },
        { type: 'tool_use', name: 'Agent', input: { description: 'run sub-task' } }
      ]}
    },
    {
      type: 'assistant', uuid: 'a2', timestamp: '2026-01-01T10:00:10Z',
      message: { content: [
        { type: 'tool_use', name: 'Edit', input: { file_path: '/src/foo.js', old_string: 'a', new_string: 'b' } }
      ]}
    }
  ]);

  const res = await request(app).get(`/api/projects/${tmpSlug}/sessions/${sid}/activity`);
  assert.strictEqual(res.status, 200);
  const { items, stats } = res.body;

  assert.strictEqual(stats.total, 5);
  assert.strictEqual(stats.byCategory.shell, 1);
  assert.strictEqual(stats.byCategory.file, 2);
  assert.strictEqual(stats.byCategory.web, 1);
  assert.strictEqual(stats.byCategory.agent, 1);

  const bash = items.find(i => i.tool === 'Bash');
  assert.ok(bash, 'Bash item present');
  assert.strictEqual(bash.category, 'shell');
  assert.strictEqual(bash.label, 'npm test');

  const webSearch = items.find(i => i.tool === 'WebSearch');
  assert.ok(webSearch);
  assert.strictEqual(webSearch.category, 'web');
  assert.strictEqual(webSearch.label, 'node docs');

  const agent = items.find(i => i.tool === 'Agent');
  assert.ok(agent);
  assert.strictEqual(agent.category, 'agent');
  assert.strictEqual(agent.label, 'run sub-task');
});

test('GET /api/projects/:slug/sessions/:sessionId/activity returns empty items for session with no tool calls', async () => {
  const tmpSlug = 'activity-empty-proj';
  const sid = 'empty111-1111-1111-1111-111111111111';
  const dir = path.join(paths.PROJECTS_DIR, tmpSlug);
  fs.rmSync(dir, { recursive: true, force: true });
  fs.mkdirSync(dir, { recursive: true });

  writeJsonl(path.join(dir, sid + '.jsonl'), [
    { type: 'user', uuid: 'u1', timestamp: '2026-01-01T10:00:00Z', message: { content: 'hello' } },
    { type: 'assistant', uuid: 'a1', timestamp: '2026-01-01T10:00:05Z', message: { content: 'hi' } }
  ]);

  const res = await request(app).get(`/api/projects/${tmpSlug}/sessions/${sid}/activity`);
  assert.strictEqual(res.status, 200);
  assert.deepStrictEqual(res.body.items, []);
  assert.strictEqual(res.body.stats.total, 0);
});

test('GET /api/projects/:slug/sessions/:sessionId/activity returns 404 for unknown session', async () => {
  const res = await request(app).get(`/api/projects/${SLUG}/sessions/no-such-session/activity`);
  assert.strictEqual(res.status, 404);
});

test('GET /api/projects/:slug/sessions/:sessionId/activity returns 400 for invalid slug', async () => {
  const res = await request(app).get('/api/projects/bad..slug/sessions/any/activity');
  assert.strictEqual(res.status, 400);
});

test('GET /api/projects/active returns active sessions with titles', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();
  activeSessions.register(SLUG, SESSION_A, 'os-terminal');

  const res = await request(app).get('/api/projects/active');
  assert.strictEqual(res.status, 200);
  assert.ok(Array.isArray(res.body));
  const entry = res.body.find(s => s.slug === SLUG && s.sessionId === SESSION_A);
  assert.ok(entry, 'active session should be present');
  assert.strictEqual(entry.kind, 'os');
  assert.ok(typeof entry.title === 'string');

  activeSessions._reset();
});

test('GET /api/projects/active returns empty when no active sessions', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();

  const res = await request(app).get('/api/projects/active');
  assert.strictEqual(res.status, 200);
  assert.deepStrictEqual(res.body, []);
});

// ── POST deactivate ───────────────────────────────────────────────────────────

test('POST /api/projects/:slug/sessions/:sessionId/deactivate returns 200 for valid session', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();
  activeSessions.register(SLUG, SESSION_A, 'os-terminal');

  const res = await request(app)
    .post(`/api/projects/${SLUG}/sessions/${SESSION_A}/deactivate`);
  assert.strictEqual(res.status, 200);
  assert.strictEqual(res.body.ok, true);

  activeSessions._reset();
});

test('POST /api/projects/:slug/sessions/:sessionId/deactivate returns 400 for invalid slug', async () => {
  const res = await request(app)
    .post('/api/projects/bad..slug/sessions/any-session/deactivate');
  assert.strictEqual(res.status, 400);
  assert.strictEqual(res.body.error, 'Invalid slug');
});

test('POST /api/projects/:slug/sessions/:sessionId/deactivate returns 400 for traversal in sessionId', async () => {
  const res = await request(app)
    .post(`/api/projects/${SLUG}/sessions/..evil/deactivate`);
  assert.strictEqual(res.status, 400);
  assert.strictEqual(res.body.error, 'Invalid session ID');
});

test('POST /api/projects/:slug/sessions/:sessionId/deactivate removes session from active list', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();
  activeSessions.register(SLUG, SESSION_A, 'os-terminal');

  await request(app).post(`/api/projects/${SLUG}/sessions/${SESSION_A}/deactivate`);

  const list = await request(app).get('/api/projects/active');
  const entry = list.body.find(s => s.slug === SLUG && s.sessionId === SESSION_A);
  assert.ok(!entry, 'deactivated session must not appear in active list');

  activeSessions._reset();
});

// ── GET /active: sessionId traversal filter ───────────────────────────────────

test('GET /api/projects/active filters out sessions with traversal characters in sessionId', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();
  // Register a session with a traversal sessionId (register() does not validate)
  activeSessions.register(SLUG, '../etc/passwd', 'os-terminal');

  const res = await request(app).get('/api/projects/active');
  assert.strictEqual(res.status, 200);
  const entry = res.body.find(s => s.sessionId === '../etc/passwd');
  assert.ok(!entry, 'sessionId with .. must be excluded from active list');

  activeSessions._reset();
});

// ── POST open-readonly / close-readonly ───────────────────────────────────────

test('POST /api/projects/:slug/sessions/:sessionId/open-readonly registers and shows up as kind "readonly"', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();

  const res = await request(app)
    .post(`/api/projects/${SLUG}/sessions/${SESSION_A}/open-readonly`)
    .send({ instanceId: 'instance-1' });
  assert.strictEqual(res.status, 200);
  assert.strictEqual(res.body.ok, true);

  const list = await request(app).get('/api/projects/active');
  const entry = list.body.find(s => s.slug === SLUG && s.sessionId === SESSION_A);
  assert.ok(entry, 'readonly session should be present');
  assert.strictEqual(entry.kind, 'readonly');
  assert.strictEqual(entry.instanceId, 'instance-1');

  activeSessions._reset();
});

test('open-readonly: the same session opened under two instance ids yields two separate entries', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();

  await request(app).post(`/api/projects/${SLUG}/sessions/${SESSION_A}/open-readonly`).send({ instanceId: 'instance-1' });
  await request(app).post(`/api/projects/${SLUG}/sessions/${SESSION_A}/open-readonly`).send({ instanceId: 'instance-2' });

  const list = await request(app).get('/api/projects/active');
  const entries = list.body.filter(s => s.slug === SLUG && s.sessionId === SESSION_A && s.kind === 'readonly');
  assert.strictEqual(entries.length, 2);
  assert.deepStrictEqual(new Set(entries.map(e => e.instanceId)), new Set(['instance-1', 'instance-2']));

  activeSessions._reset();
});

test('open-readonly: returns 400 for missing instanceId', async () => {
  const res = await request(app)
    .post(`/api/projects/${SLUG}/sessions/${SESSION_A}/open-readonly`)
    .send({});
  assert.strictEqual(res.status, 400);
});

test('open-readonly: returns 400 for invalid slug', async () => {
  const res = await request(app)
    .post('/api/projects/bad..slug/sessions/any-session/open-readonly')
    .send({ instanceId: 'instance-1' });
  assert.strictEqual(res.status, 400);
});

test('open-readonly: returns 400 for traversal in sessionId', async () => {
  const res = await request(app)
    .post(`/api/projects/${SLUG}/sessions/..evil/open-readonly`)
    .send({ instanceId: 'instance-1' });
  assert.strictEqual(res.status, 400);
});

test('close-readonly: removes only the matching instance, leaving others active', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();

  await request(app).post(`/api/projects/${SLUG}/sessions/${SESSION_A}/open-readonly`).send({ instanceId: 'instance-1' });
  await request(app).post(`/api/projects/${SLUG}/sessions/${SESSION_A}/open-readonly`).send({ instanceId: 'instance-2' });

  const res = await request(app)
    .post(`/api/projects/${SLUG}/sessions/${SESSION_A}/close-readonly`)
    .send({ instanceId: 'instance-1' });
  assert.strictEqual(res.status, 200);

  const list = await request(app).get('/api/projects/active');
  const entries = list.body.filter(s => s.slug === SLUG && s.sessionId === SESSION_A && s.kind === 'readonly');
  assert.strictEqual(entries.length, 1);
  assert.strictEqual(entries[0].instanceId, 'instance-2');

  activeSessions._reset();
});

test('readonly and a real os/browser session on the same id both appear, not deduped', async () => {
  const activeSessions = require('../lib/active-sessions');
  activeSessions._reset();
  activeSessions.register(SLUG, SESSION_A, 'os-terminal');
  await request(app).post(`/api/projects/${SLUG}/sessions/${SESSION_A}/open-readonly`).send({ instanceId: 'instance-1' });

  const list = await request(app).get('/api/projects/active');
  const entries = list.body.filter(s => s.slug === SLUG && s.sessionId === SESSION_A);
  assert.strictEqual(entries.length, 2);
  assert.deepStrictEqual(new Set(entries.map(e => e.kind)), new Set(['os', 'readonly']));

  activeSessions._reset();
});
